version = "1.0.4"
description = "Parser for report.json files, generated by https://github.com/ben-manes/gradle-versions-plugin"

plugins {
    id("java-library")
    kotlin("jvm")
    kotlin("plugin.serialization") version "1.5.0"
    id("maven-publish")
    publish
}

kotlin {
    explicitApi()
}

dependencies {
    implementation(Lib.kotlinxSerializationJson)

    testImplementation(Lib.testJunit)
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}
